### ISSUE TITLE
Process dies when running with https after http request

### ISSUE THREAD

**Issue by alecalve** [shesek/spark-wallet#10]
```
$ spark-wallet -i 0.0.0.0
...
HTTPS server running on https://0.0.0.0:9737
```

running this in another term:

```
$ curl http://localhost:9737
curl: (52) Empty reply from server
```

Logs are:

```
uncaughtException, stopping process                 
TypeError: ParserIncomingMessage is not a constructor                                                    
    at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)                                        
    at socketOnData (_http_server.js:472:20)        
    at Socket.emit (events.js:180:13)               
    at Socket.Readable.read (_stream_readable.js:487:10)                                                 
    at flow (_stream_readable.js:858:34)            
    at resume_ (_stream_readable.js:840:3)          
    at process._tickCallback (internal/process/next_tick.js:178:19) 
```

**Comment by shesek** [comment]
Ugh. This is probably related to https://github.com/shesek/spark-wallet/commit/62798caf243415d4194d5dc6b6e7bf388bb00d02. Which version of nodejs are you running?

**Comment by shesek** [comment]
Are you able to access the server using `https://`?

**Comment by alecalve** [comment]
`https://` works fine.

```
$ node -v
v9.11.2
```

**Comment by alecalve** [comment]
It does! Thanks for the quick fix.
