### ISSUE TITLE
clightning v0.7.3rc3 "Unknown command 'listpayments'"

### ISSUE THREAD

**Issue by instagibbs** [shesek/spark-wallet#122]
Is the RC expected to work?

**Comment by kalibox** [comment]
I'm seeing the same error message on the latest version of clightning that was release late last night- v0.7.3 (not RC.

**Comment by instagibbs** [comment]
I was getting this on my browser, Ctrl-shift-r got rid of the cached data.

**Comment by instagibbs** [comment]
you're probably using the cached version of the spark wallet, or haven't updated. Make sure you're running 0.2.9

**Comment by kalibox** [comment]
Thank you, I'll try that now. Cheers.

**Comment by kalibox** [comment]
Thats done the trick. Thanks!

**Comment by pavlenex** [comment]
@shesek 

I'm experiencing the same error on MacOS.

`Unknown command 'listpayments'`

![Screenshot 2019-11-01 at 13 29 55](https://user-images.githubusercontent.com/36959754/68024912-b94dc680-fcab-11e9-853f-445ebc34d4d1.png)

```
LightningError: Unknown command 'listpayments'
    at createError (/opt/spark/node_modules/error/typed.js:40:22)
    at LightningClient.once.res (/opt/spark/node_modules/clightning-client/index.js:107:28)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at LightningClient.emit (events.js:211:7)
    at Interface.LightningClient.rl.on.line (/opt/spark/node_modules/clightning-client/index.js:62:17)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._normalWrite (readline.js:422:12)
```

**Comment by shesek** [comment]
As can be seen on the footer, it appears like you're still running v0.2.8 (the spark version with c-lightning v0.7.3 compatibility is v0.2.9). Are you sure the server-side is running the latest version?

If you're accessing with the browser, did you try doing a hard refresh (Ctrl-shift-r) to clear your browser cache? Or if you're using the Electron desktop app, did you update it to the latest version too?
