### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by PsySc0rpi0n** [shesek/spark-wallet#161]
Hello.
Some basic info first:
My OS: Debian Buster 10 64 bit
My Spark-Wallet version: the one installed by 'npm' command from instructions

This is probably for a HELP tag

I have this working before yesterday, but after a reboot something went wrong.

I followed the instructions to avoid permission problems.
I created the ~/.npm-global
I added the line 'export PATH=~/.npm-global/bin:$PATH' to .profile file and sourced it.
I installed spark-wallet using the provided 'npm' command in instructions and get this output:

>$ npm install -g spark-wallet 
>npm WARN npm npm does not support Node.js v10.21.0
>npm WARN npm You should probably upgrade to a newer version of node as we
>npm WARN npm can't make any promises that npm will work with this version.
>npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
>npm WARN npm You can find the latest version at https://nodejs.org/
>/home/psysc0rpi0n/.npm-global/bin/spark-wallet -> /home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/cli.js

>core-js@2.6.11 postinstall /home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/@babel/polyfill/node_modules/core-js
>node -e "try{require(\'./postinstall\')}catch(e){}"

>Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

>The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

>Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

>core-js@3.6.5 postinstall /home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/core-js
>node -e "try{require('./postinstall')}catch(e){}"

>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/spark-wallet/node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

>+ spark-wallet@0.2.17
>added 578 packages from 270 contributors in 8.579s

and when I try to start the server, I get this:

>$ spark-wallet 
>unhandledRejection, stopping process
>Error: The rpcPath must be an absolute path
    >at new LightningClient (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/clightning-client/index.js:19:19)
    >at module.exports.rpcPath (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/clightning-client/index.js:138:29)
    >at _callee$ (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:53:72)
    >at tryCatch (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:63:40)
    >at Generator.invoke [as _invoke] (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:293:22)
    >at Generator.next (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:118:21)
    >at asyncGeneratorStep (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:15:103)
    >at _next (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:17:194)
    >at /home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:17:364
    >at new Promise (<anonymous>)
>Error: The rpcPath must be an absolute path
    >at new LightningClient (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/clightning-client/index.js:19:19)
    >at module.exports.rpcPath (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/clightning-client/index.js:138:29)
    >at _callee$ (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:53:72)
    >at tryCatch (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:63:40)
    >at Generator.invoke [as _invoke] (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:293:22)
    >at Generator.next (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:118:21)
    >at asyncGeneratorStep (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:15:103)
    >at _next (/home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:17:194)
    >at /home/psysc0rpi0n/.npm-global/lib/node_modules/spark-wallet/dist/app.js:17:364
    >at new Promise (<anonymous>)`

**Comment by shesek** [comment]
Can you try specifying `--ln-path <dir>` with the path to your c-lightning data directory?

It should automatically use `~/.lightning/<network>`, but it seems like its not able to detect your home directory for some reason.

**Comment by PsySc0rpi0n** [comment]
@shesek it worked. I've been noticing something though. The line we add in ~/.profile is supposed to make the export command persistent, right? Even if you reboot, change terminal session, etc, this ~/.profile should be sourced automatically and I think it has not being sourced because when I open a new terminal and run `echo $PATH` I don't see ~/.npm-global/bin` added there.

**Comment by shesek** [comment]
Yes, `.profile` should automatically get loaded in new terminals. I'm not sure what could be causing it not to :o

**Comment by PsySc0rpi0n** [comment]
> Yes, `.profile` should automatically get loaded in new terminals. I'm not sure what could be causing it not to :o

I'll try to figure it out and if I do, I'll write what was wrong here!

**Comment by PsySc0rpi0n** [comment]
Recently I have moved to SFCE desktop and I still haven't figured out why logging out and back in is not sourcing my .profile file. Therefore, the $PATH is not correctly updated and spark-wallet returns this problem.
