### ISSUE TITLE
Funding failed due to internal error

### ISSUE THREAD

**Issue by joelmackie** [shesek/spark-wallet#197]
received the following message when attempting to open a channel:

LightningError: They sent error channel 0a9xxxxxxxxxxxxxxxxxxxxxx: funding failed due to internal error
    at createError (/usr/local/lib/node_modules/spark-wallet/node_modules/error/typed.js:40:22)
    at LightningClient.once.res (/usr/local/lib/node_modules/spark-wallet/node_modules/clightning-client/index.js:122:28)
    at Object.onceWrapper (events.js:286:20)
    at LightningClient.emit (events.js:198:13)
    at Interface.LightningClient.rl.on.line (/usr/local/lib/node_modules/spark-wallet/node_modules/clightning-client/index.js:76:17)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._normalWrite (readline.js:451:12)
    at Socket.ondata (readline.js:165:10)
    at Socket.emit (events.js:198:13)
I had a power failure about a week ago and lost data.  was able to get Spark-Wallet and C-lightning working again but it seems like something is still off.  I did lose some funds and my channels however they are still showing active on 1ml

**Comment by joelmackie** [comment]
Another issue is that when I click the Receive button I get the spinning circle and it will not go past that. I have to back out as the spinning circle will not go away.  Any help with these issues would be greatly appreciated.
