### ISSUE TITLE
Zeus wallet triggers 500-error on load

### ISSUE THREAD

**Issue by cbergqvist** [shesek/spark-wallet#201]
Spark wallet log:
```
2022-06-08T20:48:59.035310Z TypeError: Invalid attempt to spread non-iterable instance.
2022-06-08T20:48:59.035711Z In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
2022-06-08T20:48:59.035952Z     at _nonIterableSpread (/usr/local/lib/node_modules/spark-wallet/dist/app.js:11:39)
2022-06-08T20:48:59.036192Z     at _toConsumableArray (/usr/local/lib/node_modules/spark-wallet/dist/app.js:9:131)
2022-06-08T20:48:59.036410Z     at _callee$ (/usr/local/lib/node_modules/spark-wallet/dist/app.js:131:82)
2022-06-08T20:48:59.036606Z     at tryCatch (/usr/local/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:63:40)
2022-06-08T20:48:59.036770Z     at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:293:22)
2022-06-08T20:48:59.036953Z     at Generator.next (/usr/local/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:118:21)
2022-06-08T20:48:59.037107Z     at asyncGeneratorStep (/usr/local/lib/node_modules/spark-wallet/dist/app.js:21:103)
2022-06-08T20:48:59.037241Z     at _next (/usr/local/lib/node_modules/spark-wallet/dist/app.js:23:194)
2022-06-08T20:48:59.037424Z     at /usr/local/lib/node_modules/spark-wallet/dist/app.js:23:364
2022-06-08T20:48:59.037629Z     at new Promise ()
2022-06-08T20:48:59.038727Z POST /rpc 500 4.322 ms - 131
```
Running on Start9 Embassy, Spark version 0.3.1~3.

**Comment by ghost** [comment]
This is likely caused by Zeus passing `{ ... }` objects as parameters to Spark instead of an array `[ .. ]`.

Zeus likely never supported the (original) Spark server but only the c-lightning plugin **Sparko**, which does accept `{ ... }` objects. See also #206
