### ISSUE TITLE
spark no longer working after the great msat migration of CLN v23.05

### ISSUE THREAD

**Issue by pabpas** [shesek/spark-wallet#209]
Upgraded today to CLN v23.05rc1 and spark-wallet stops working with:
```
decoded.amount_msat.slice is not a function 
```
Apparently due to "the Great Msat Migration started in v0.12.0, so "msat" fields are no longer strings with "msat" appended, but simply integers."

https://github.com/ElementsProject/lightning/pull/5986

**Comment by Dominion5254** [comment]
Can you provide more info on what you did to produce this error?

Does the same error present on the [latest](https://github.com/ElementsProject/lightning/releases/tag/v23.05)?

**Comment by pabpas** [comment]
Nothing special to produce, just launch spark-wallet with:
```
$ ./node_modules/.bin/spark-wallet --onion
```
And this is the output after logging in:
```
TypeError: decoded.amount_msat.slice is not a function
    at _callee7$ (/home/user/node_modules/spark-wallet/dist/cmd.js:314:108)
    at tryCatch (/home/user/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/user/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/user/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/user/node_modules/spark-wallet/dist/cmd.js:41:103)
    at _next (/home/user/node_modules/spark-wallet/dist/cmd.js:43:194)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
spark v0.3.1
cln 23.05rc4, which AFAIK is the same as the final release.

**Comment by btcteun** [comment]
Can confirm this. I just updated to cln 23.05 and my spark-wallet stopped working with the same error. 
I run spark in docker, spark version v0.3.1

**Comment by JaviLib** [comment]
Is this app maintained? It seems that this trivial error is not corrected anymore.

**Comment by 3cola** [comment]
I owuld say that the problem seems to come from this line (and/or the next...): 
https://github.com/shesek/spark-wallet/blob/112fd9bb835f4ee10feeeb46d6c6ebeb78db1c61/client/src/util.js#L32

I would guess that you can simplify the parse function for the new cln versions as we don´t need anymore to remove the last 4 chars in the slice to remove 'msat'.

**Comment by 3cola** [comment]
I made a fork for this repo, and I made a commit that should fix the issue of the great msat migration of CLN v23.05.
Along the way, I also changed the defaults to expert mode, display the amounts in sats, and the default theme to darkly.
