### ISSUE TITLE
--onion no longer works, torbrowser bundle download URL is now 404

### ISSUE THREAD

**Issue by weissjeffm** [shesek/spark-wallet#211]
```
[jweiss@home node_modules]$ spark-wallet --onion
WARN: /home/jweiss/.lightning/lightning-rpc is missing, using the bitcoin mainnet subdirectory at /home/jweiss/.lightning/bitcoin instead.
WARN: specifying the main lightning data directory is deprecated, please specify the network directory explicitly.

Connected to c-lightning v0.12.0-122-g5b58eda with id 03f38c29324df9f7e1ee76b055e2199a7f4175d141d44eeeabc5fed40f9929b0b8 on network bitcoin at /home/jweiss/.lightning/bitcoin/lightning-rpc

Tor Hidden Service enabled (via --onion) for the first time, downloading the Tor Bundle...
The Spark .onion server will start automatically when its ready.

In the meanwhile, you can access the local HTTP server directly.


HTTP server running on http://localhost:8000
npm ERR! code 1
npm ERR! path /home/jweiss/.nvm/versions/node/v18.16.0/lib/node_modules/spark-wallet/dist/transport/granax-dep/node_modules/@deadcanaries/granax
npm ERR! command failed
npm ERR! command sh -c node script/download-tbb.js
npm ERR! Downloading Tor Bundle from https://dist.torproject.org/torbrowser/12.0.7/tor-browser-linux64-12.0.7_en-US.tar.xz...
npm ERR! Failed to download Tor Bundle, status code: 404

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jweiss/.npm/_logs/2023-06-10T14_19_19_524Z-debug-0.log
unhandledRejection, stopping process
Error: Tor installation failed, exited with code 1
    at ChildProcess.<anonymous> (/home/jweiss/.nvm/versions/node/v18.16.0/lib/node_modules/spark-wallet/dist/transport/granax-dep/index.js:50:55)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
Error: Tor installation failed, exited with code 1
    at ChildProcess.<anonymous> (/home/jweiss/.nvm/versions/node/v18.16.0/lib/node_modules/spark-wallet/dist/transport/granax-dep/index.js:50:55)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

This url is no longer accessible https://dist.torproject.org/torbrowser/12.0.7/tor-browser-linux64-12.0.7_en-US.tar.xz

This seems to be coming from the granax package, but it's strange, I don't have any `download-tbb.js` anywhere on my system, if I could find it I might be able to just update the URL.

**Comment by m46nus** [comment]
Hi you can use this to use system tor: 

\# GRANAX_USE_SYSTEM_TOR=1 spark-wallet --onion --pairing-url

or put this into your torrc

HiddenServicePort 9737 127.0.0.1:9737
