### ISSUE TITLE
greenlock not installed 

### ISSUE THREAD

**Issue by zundg** [shesek/spark-wallet#30]
When installing spark-wallet using letsencrypt features cause a crash as greenlock is missing, guess it's not specified as dependency?

**Comment by shesek** [comment]
It definitely is specified, but its marked as an optional dependency, such that failing to install greenlock for whatever reason won't abort Spark's installation entirely.

Can you look at the installation log and see if there are any warnings related to greenlock?

**Comment by zundg** [comment]
I have not much clue of npm/node etc, so maybe these warnings could have pointed to that. here is the log:

root@test:~# curl -sL https://deb.nodesource.com/setup_10.x | bash -

## Installing the NodeSource Node.js 10.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease
Hit:3 http://ftp.debian.org/debian stretch-updates InRelease
Hit:4 http://ftp.debian.org/debian stretch Release 
Reading package lists... Done

## Installing packages required for setup: apt-transport-https lsb-release...

+ apt-get install -y apt-transport-https lsb-release > /dev/null 2>&1

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/stretch/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 10.x repo...

+ echo 'deb https://deb.nodesource.com/node_10.x stretch main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_10.x stretch main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease
Hit:3 http://ftp.debian.org/debian stretch-updates InRelease
Hit:4 http://ftp.debian.org/debian stretch Release 
Get:5 https://deb.nodesource.com/node_10.x stretch InRelease [4612 B]
Get:7 https://deb.nodesource.com/node_10.x stretch/main amd64 Packages [767 B]
Fetched 5379 B in 1s (4084 B/s)
Reading package lists... Done

## Run `sudo apt-get install -y nodejs` to install Node.js 10.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


root@test:~# apt install nodejs build-essential libssl-dev git
[...]
root@test:~# npm install -g spark-wallet
/usr/bin/spark-wallet -> /usr/lib/node_modules/spark-wallet/dist/cli.js

> ursa-optional@0.9.8 install /usr/lib/node_modules/spark-wallet/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:115
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1168:35)
    at Object.<anonymous> (/usr/lib/node_modules/spark-wallet/node_modules/ursa-optional/rebuild.js:9:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa-optional@0.9.8 (node_modules/spark-wallet/node_modules/ursa-optional):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa-optional@0.9.8 install: `node rebuild.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ spark-wallet@0.1.2
added 233 packages from 132 contributors in 34.291s

[getting bitcoin-cli, lightningd etc setup]

root@test:~# spark-wallet -i 192.168.172.199 --tls-name $HOST --letsencrypt $EMAIL --port 8080
Connected to c-lightning v0.6.1-125-gd6fcfe0 with id 02d1dc1a16512b2d9cdfc4df2f0fb325524053ec99d9a249df23a23ed902e0a9fe on network bitcoin at /root/.lightning/lightning-rpc
No LOGIN or --login specified, picked username "ccmbe" with password "zbXjRuGgfkebCVO"
Setting up LetsEncrypt CA-signed TLS cert for $HOST with email $EMAIL in /root/.spark-wallet/tls
unhandledRejection, stopping process
Error: Cannot find module 'greenlock'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at letsencrypt (/usr/lib/node_modules/spark-wallet/dist/transport/tls.js:97:12)
    at module.exports (/usr/lib/node_modules/spark-wallet/dist/transport/tls.js:44:26)
    at _callee$ (/usr/lib/node_modules/spark-wallet/dist/app.js:91:58)
    at tryCatch (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:117:21)
Error: Cannot find module 'greenlock'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at letsencrypt (/usr/lib/node_modules/spark-wallet/dist/transport/tls.js:97:12)
    at module.exports (/usr/lib/node_modules/spark-wallet/dist/transport/tls.js:44:26)
    at _callee$ (/usr/lib/node_modules/spark-wallet/dist/app.js:91:58)
    at tryCatch (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:117:21)
root@test:~#

**Comment by shesek** [comment]
This might be due to some permission issues. I suggest to run `npm install` and `spark-wallet` with a non-root user and follow [the instructions here](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory) to configure a local npm installation directory.
