### ISSUE TITLE
Having Tls problem Error: Cannot find module 'greenlock'

### ISSUE THREAD

**Issue by emonazad** [shesek/spark-wallet#36]
Hi, First i like to say Thank you for bringing this project to live.I'm having some issue with tls.When i try to 
--letsencrypt=test@test.com

its giving me Error -

UnhandledRejection, stopping process
Error: Cannot find module 'greenlock'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at letsencrypt (/usr/lib/node_modules/spark-wallet/dist/transport/tls.js:97:12)
    at module.exports (/usr/lib/node_modules/spark-wallet/dist/transport/tls.js:44:26)
    at _callee$ (/usr/lib/node_modules/spark-wallet/dist/app.js:91:58)
    at tryCatch (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/spark-wallet/node_modules/regenerator-runtime/runtime.js:117:21)

And When i try to just use default tls which was created by spark-wallet it hangs at Performing tls handshake.

I have changed the Let's encrypt verification server port to : random 7474

since port 80 is blocked by isp.
i hoping Let's encrypt verification isnt working since port is not being used which i have set 7474.

I can acess spark-wallet if i set no-tls .but i wanted to know whats the main reason behind https hangs at performing tls handshake ? 

I have changed dns nameserver 8.8.8.8 and 8,8,4,4 changed the mtu settings.tried so many method to fix it.it doesnt fix.

Thank you hoping to get a great solution .

**Comment by emonazad** [comment]
Update : it seems --letsencrypt=test@test.com is working on non root user . installed spark with non root user. but having tls handshake problem it hangs while using https .

**Comment by shesek** [comment]
> Error: Cannot find module 'greenlock'

greenlock is defined as an optional dependency, Spark will still install if greenlock fails to install for whatever reason. Look at the `npm install` logs to see if there are any errors there.

> I have changed the Let's encrypt verification server port to : random 7474

Note that for LetsEncrypt to work, you must be able to receive requests on port 80. If you start it on a different port, you'll need to forward port 80 to it. See the [TLS docs](https://github.com/shesek/spark-wallet/blob/master/doc/tls.md) for more details.

Also, you must have a (sub)domain name pointed at your server. LetsEncrypt can't be used with IP addresses.

> but i wanted to know whats the main reason behind https hangs at performing tls handshake ?

Is this happening even if you don't enable LetsEncrypt?

**Comment by emonazad** [comment]
>      

Is this happening even if you don't enable LetsEncrypt?

Thanks for you replay. :) . this happens when i enable tls function on spark and browse the https it just shows  performing tls handshake and hangs on it.

and if i disable tls function no-tls=1 http seems to work and if i browse https i get ssl_error_rx_record_too_long eror message.
