### ISSUE TITLE
Can't run spark wallet

### ISSUE THREAD

**Issue by instagibbs** [shesek/spark-wallet#39]
```
spark-wallet -l lightningd/lightningd
/usr/local/lib/node_modules/spark-wallet/node_modules/meow/index.js:66
    const {pkg} = options;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/spark-wallet/dist/cli.js:6:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by shesek** [comment]
Which version of nodejs are you running? Spark requires at least v6.0, but the latest v8.x.x is preferable.

Instructions for installation using various package managers are [available here](https://nodejs.org/en/download/package-manager/), or you can use `n`: `$ npm install -g n && n 8.11.3`. You might have to reinstall Spark after doing that.

**Comment by instagibbs** [comment]
Ok, having different npm fights but I think this isn't a spark wallet issue now at least.
