### ISSUE TITLE
Error when running with --onion

### ISSUE THREAD

**Issue by LightningK0ala** [shesek/spark-wallet#7]
Fails when running spark-wallet with the `--onion` option (either via npx or npm global install):
```
unhandledRejection, stopping process
Error: Tor exited with code 2
    at ChildProcess.child.on (/home/odroid/.nvm/versions/node/v8.11.1/lib/node_modules/spark-wallet/dist/transport/hsv3-dep/node_modules/granax/index.js:73:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
Error: Tor exited with code 2
    at ChildProcess.child.on (/home/odroid/.nvm/versions/node/v8.11.1/lib/node_modules/spark-wallet/dist/transport/hsv3-dep/node_modules/granax/index.js:73:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

Node version: 8.11.1
npm version: 5.6.0
OS: Linux odroid 4.14.37-135 #1 SMP PREEMPT Sun Apr 29 23:34:43 -03 2018 armv7l armv7l armv7l GNU/Linux

**Comment by shesek** [comment]
Can you try running tor directly and check if it outputs any error? Try this:

```bash
$ cd /home/odroid/.nvm/versions/node/v8.11.1/lib/node_modules/spark-wallet/dist/transport/hsv3-dep/node_modules/granax/bin/tor-browser_en-US/Browser/TorBrowser/Tor
$ LD_LIBRARY_PATH=`pwd` ./tor -f /home/odroid/.spark-wallet/tor/torrc
```

**Comment by LightningK0ala** [comment]
Getting this error `-bash: ./tor: cannot execute binary file: Exec format error`

**Comment by shesek** [comment]
It looks like Tor doesn't publish official pre-built binaries for ARM.

It should work if you compile it yourself, or if you fetch them from a 3rd party package repository that has an ARM version (Debian, Fedora and Arch have it). But since Spark is downloading the official release (via [granax](https://gitlab.com/bookchin/granax/blob/master/script/download-tbb.js)), it won't work on ARM.

You should be able to get this working if you install Tor on your system with your package manager, then start Spark with the environment variable `GRANAX_USE_SYSTEM_TOR=1` (or `--granax-use-system-tor 1` as an argument).

**Comment by shesek** [comment]
Not much I can do about this unfortunately, closing for now.
